URLTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: URLTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: PK  # UUID
        AttributeType: S
      - AttributeName: SK  # Creation Time
        AttributeType: S
      - AttributeName: LSI1SK # Expiration Time
        AttributeType: S
      # - AttributeName: TTL # Expiration Time
      #   AttributeType: N
    LocalSecondaryIndexes: 
      - IndexName: LSI1
        KeySchema: 
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: LSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    TimeToLiveSpecification:
      AttributeName: TTL
      Enabled: true


Outputs:
  URLTableArn:
    Value: 
      "Fn::GetAtt": [ URLTable, Arn ]
    Export:
      Name: URLTable-${self:provider.stage}-Arn
  
  URLTableName:
    Value: 
      Ref: URLTable
    Export:
      Name: URLTable-${self:provider.stage}-Name